### ISSUE TITLE
Provide Python debugger

### ISSUE THREAD

**Issue by webwurst** [solo-io/kubesquash#1]
Just creating this issue so that I am subscribed for this. Happy to test when something shows up in this direction :)

**Comment by yuval-k** [comment]
What's your python debugger that you use? to my understanding there is standard debugger that allows you to attach to a running python process, so would love to have more insight here!

Any other feedback is appriciated

**Comment by mafrosis** [comment]
[`pdb`](https://docs.python.org/3/library/pdb.html) is the standard Python debugger, available in all versions.

[`ipdb`](https://pypi.org/project/ipdb/) is a more fully-featured alternative that requires a bunch of additional python package dependencies.

**Comment by inviscid** [comment]
I would be interested in helping add this feature but would need some guidance to get started.  Would also like to add some integration to PyCharm if possible too.

**Comment by yuval-k** [comment]
we are actually in the process of making all the squash debuggers work in kubesquash as well. this should happen in the next few weeks.
closing as answered.
