### ISSUE TITLE
0.1.9 kubesquash binary does not work on Fedora

### ISSUE THREAD

**Issue by bartoszmajsak** [solo-io/kubesquash#16]
First of all many thanks for these handy debugging tools! It's really great to have such a tool for day-to-day k8s app development.

It seems that the latest version has been built using [musl-libc](https://www.musl-libc.org) which is not packaged by default in Fedora, resulting in quite an unhelpful error message `zsh: no such file or directory ` while trying to execute `ksquash`. 

In contrary, the previous version has been built using system `libc`.

```
╰─ file ~/.asdf/installs/kubesquash/v0.1.8/bin/ksquash
/home/bartek/.asdf/installs/kubesquash/v0.1.8/bin/ksquash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
```

```
╰─ file ~/.asdf/installs/kubesquash/v0.1.9/bin/ksquash
/home/bartek/.asdf/installs/kubesquash/v0.1.9/bin/ksquash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped
```

We should either document how to get `musl-libc` OR use `netgo` with `CGO_ENABLED=0` while building binaries (it seems that we only use `net` package requiring `libc` - please correct if I'm wrong). 

Happy to contribute whatever you feel is the right way.

Also, it seems that both 0.1.8 and 0.1.9 tags point to the same commit.

**Comment by yuval-k** [comment]
it must be something that changed in go, because i don't recall changing to musl-libc... anyway i think building with `CGO_ENABLED=0` should just work.
IIRC netgo is needed for squash and is run in a container so there should be no problem to disable cgo for kubesquash.

**Comment by bartoszmajsak** [comment]
> it must be something that changed in go, because i don't recall changing to musl-libc.

Were both `0.1.8` and `0.1.9` built on the same machine? Anyway - there's a PR now.
