### ISSUE TITLE
Correct Usage of VS Extention

### ISSUE THREAD

**Issue by GMScribe** [solo-io/kubesquash#6]
Hi guys,

I have a pod running a C++ program and I'm able to attach gdb to my pod via ./kubesquash-linux --debugger gdb, however, when I attempt to use the KubeSquash VS Code extension I simply receive the message "Configured debug type 'go' is not supported".

What must I do to resolve?

Many thanks

**Comment by yuval-k** [comment]
Yes as currently the extension only supports the go debugger. To resolve it, the extension needs to be modified. We plan to do it, but it will take us a bit of time to do.

**Comment by cscetbon** [comment]
Using the go extension, I get https://pastebin.com/raw/z3wvTT4h when I try to debug a running go pod. Any idea ?

**Comment by cscetbon** [comment]
@yuval-k any idea ? 👆

**Comment by yuval-k** [comment]
Closing as answered. feel free to re-open if needed.
We are process of making all the debuggers work in both squash and kubesquash
