### ISSUE TITLE
Context deadline exceed

### ISSUE THREAD

**Issue by allamand** [solo-io/kubesquash#7]
Hi,

I'm giving a try to kubesquash on a osx with a remote kubernetes cluster.

I get this error : 

```
kubesquash
? Select a namespace myspc
? Select a pod mypod-74cd4db47d-hw2tn
? Going to attach dlv to pod mypod-74cd4db47d-hw2tn. continue? Yes

Can't get logs from errored pod
context deadline exceeded
```

Is there somehting i am missing ?

Thanks

Sébastien

**Comment by yuval-k** [comment]
can you run it with no clean, like so:
`
kubesquash -no-clean
`
then, after the error, please provide the following debug info:
`
kubectl -nsquash describe pod
kubectl -nsquash logs -l squash=kubesquash-container
`
to clean up, you can do
`
kubectl -nsquash delete pod -l squash=kubesquash-container
`

**Comment by allamand** [comment]
Hi Yuval, 

Very useful comment 👍
```
k get pods -n squash
NAME                        READY     STATUS             RESTARTS   AGE
kubesquash-containerl6nq6   0/1       ImagePullBackOff   0          8m
```
I'm working in private kubernetes with no internet access, I need to find a way to load a custom docker image for the kubesquash-container

**Comment by allamand** [comment]
@yuval-k thanks to you command I found a way to make it works copying the image in a private registry and running : 

```
kubesquash --container-repo myprivateregistry
```

Is it possible to customize the `container-repo` with the VSCode plugin ?

Thanks

**Comment by allamand** [comment]
This issue is resolved, i created a new one for dealing with private registry https://github.com/solo-io/kubesquash/issues/8
