### ISSUE TITLE
Vscode: Allow to customize remotePath

### ISSUE THREAD

**Issue by allamand** [solo-io/kubesquash#9]
Using Kubesquash vscode plugin, I add to customize the remotePath in the debug configuration so that it allows me to set breakpoints in my local code : 

```
remotePath: "/go/src/path/to/my/app"
```

It would be nice that the plugin easilly allow the user to configure that value

**Comment by yuval-k** [comment]
this is fixed in the latest version of the extension v0.1.9 (this is the relevant commit e29f25e4b2544be9716d312660ed00f8e2889db0)
